name: Deploy code to kubernetes
on: [push]
env:
  DOCKER_REGISTRY: harbor.bratislava.sk
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.HARBOR_TOKEN }}
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next
    steps:
    - name: Setup envsubst and buildx
      run: |
          mkdir -p ~/.docker/cli-plugins
          curl -s https://api.github.com/repos/docker/buildx/releases/latest | grep "browser_download_url.*linux-amd64" | cut -d : -f 2,3 | tr -d \" | wget -O ~/.docker/cli-plugins/docker-buildx -qi -
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx version
          sudo apt-get update
          sudo apt-get install gettext-base
          
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup yarn
      run: npm install -g yarn

    - uses: actions/checkout@v3
      name: Checkout repository
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Yarn install dependencies
      run: yarn --frozen-lockfile
      
    - name: Git fetch changes for bratiska-cli
      run: git fetch
      
    - name: Yarn install bratiska-cli
      run: yarn global add bratislava/bratiska-cli
      
    - name: Run Bratiska-cli
      run: bratiska-cli deploy --dry_run
