name: Deploy code to kubernetes
on: [push]
env:
  DOCKER_REGISTRY: harbor.bratislava.sk
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.HARBOR_TOKEN }}
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next
    steps:
    - uses: actions/checkout@v3
    - name: Install Prerequisites -  Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Prerequisites - envsubst
      run: docker buildx version
           sudo apt-get update
           sudo apt-get install gettext-base    
    - run: yarn --frozen-lockfile
    - run: yarn global add bratislava/bratiska-cli
    - run: git fetch
    - run: bratiska-cli deploy --dry_run
