name: Deploy code to kubernetes
on: [push]
jobs:
  deploy:
    name: Setting up
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: yarn --frozen-lockfile
    - run: yarn global add bratislava/bratiska-cli
    - run: bratiska-cli deploy --dry_run
